AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for s3 bucket

Resources:
  # Create the bucket to contain the website HTML
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: ng-cloudformation-bucket
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled

  # Public access to all users
  ReadPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal: "*"

Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket
  S3BucketUrl:
    Description: "S3 Bucket Url"
    Value: !GetAtt "S3Bucket.WebsiteURL"
